name: actions-ruby default MSYS2

on: [push, pull_request]

jobs:
  build:
    name: >-
      Ruby: ${{ matrix.ruby }}
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.3.x', '2.4.x', '2.5.x', '2.6.x', '2.7.x', '9.9.x' ]
    steps:
      - name: Install Ruby
        uses: MSP-Greg/actions-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: List MinGW packages
        run:  pacman -Q

      - name: Ruby Info
        run:  |
          ruby -v
          $abi_vers = &ruby.exe -e "STDOUT.write RUBY_VERSION"
          if ($abi_vers -ge '2.4.0') {
            ruby -e "gv = RbConfig::CONFIG['CC_VERSION_MESSAGE'][/[^\n]+/]; puts 'Built With:  ' + gv"
            ridk version
          }

      - name: where check
        run: |
          # show where
          Write-Host
          $where = 'gcc.exe', 'make.exe', 'libcrypto-1_1-x64.dll', 'libssl-1_1-x64.dll'
          foreach ($e in $where) {
            $rslt = where.exe $e 2>&1 | Out-String
            if ($rslt.contains($e)) { Write-Host $rslt }
            else { Write-Host "`nCan't find $e" }
          }
