name: actions-ruby update MSYS2

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: >-
      Ruby: ${{ matrix.ruby }}
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4.x', '2.5.x', '2.6.x', '9.9.x' ]
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Install Ruby, update MSYS2
      uses: MSP-Greg/actions-ruby@master
      with:
        ruby-version: ${{ matrix.ruby }}
        base: update
        mingw: openssl
        msys2: bison
    - name: List MinGW packages
      run:  pacman -Q
    - name: Ruby Info
      run:  |
        ruby -v
        ruby -e "gv = RbConfig::CONFIG['CC_VERSION_MESSAGE'][/[^\n]+/]; puts 'Built With:  ' + gv"
        ridk version
    - name: Where is?
      run:  |
        write-host ''
        write-host "----------------------- openssl"; where.exe openssl.exe
        write-host "----------------------- make"   ; where.exe make.exe
        write-host "----------------------- gcc"    ; where.exe gcc.exe
        write-host "----------------------- ruby"   ; where.exe ruby.exe

