name: actions-ruby update MSYS2

on: [push, pull_request]

jobs:
  build:
    name: >-
      Ruby: ${{ matrix.ruby }}
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, mingw, mswin ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ./
        with:
          ruby-version: ${{ matrix.ruby }}
          base:  update
          mingw: openssl
          msys2: bison

      - name: Ruby Info
        run:  |
          ruby -v
          ruby -e "gv = RbConfig::CONFIG.fetch('CC_VERSION_MESSAGE', ' ')[/[^\n]+/]; puts 'Built With:  ' + gv"
          openssl.exe version

      - name: List MinGW packages
        run:  pacman.exe -Q
        if: matrix.ruby != 'mswin'

      - name: where check
        run: |
          # show where
          $ErrorActionPreference = 'Continue'
          echo ''
          $where = 'gcc.exe', 'make.exe', 'bison.exe', 'openssl.exe', 'libcrypto-1_1-x64.dll', 'libssl-1_1-x64.dll'
          foreach ($e in $where) {
            $rslt = where.exe $e 2>&1 | Out-String
            if ($rslt.contains($e)) { echo $rslt }
            else { echo "`nCan't find $e" }
          }
          $LASTEXITCODE = 0